version: '3'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "23306:3306"
    volumes:
      - db_mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: quintor_pw
      MYSQL_DATABASE: cddb_quintor
      MYSQL_USER: cddb_quintor
      MYSQL_PASSWORD: quintor_pw
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER  --password=$$MYSQL_PASSWORD  --execute \"SHOW DATABASES;\""
      interval: 30s
      timeout: 10s
      retries: 5
  cddb_backend:
    depends_on:
      - mysql
    image: cddb_backend
    ports:
      - "28080:8080"
    restart: always
  cddb-frontend:
    depends_on:
      - cddb_backend
    image: cddb_frontend
    ports:
      - "20080:80"
    restart: always
volumes:
  db_mysql_data:
